WFP-VAM/prism-app

- src/components/MapView/Boundaries/__snapshots__/index.test.tsx.snap
- src/components/MapView/Boundaries/index.test.tsx
- src/components/MapView/Boundaries/index.tsx
- src/components/MapView/index.test.tsx
- src/components/MapView/index.tsx
This implements the basic functionalities required to display the admin boundaries and get info on click.
Screenshot:
> Load admin boundaries

- package.json
- src/components/DataDrawer/Chart/index.tsx
Current `master` was giving me (with both Node 12 & 13)
```
Failed to compile.
./src/components/DataDrawer/Chart/index.tsx
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/extensions
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/no-unresolved
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/named
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/no-extraneous-dependencies
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/no-duplicates
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/order
Line 1:1:   Resolve error: unable to load resolver "import/parsers"  import/no-self-import
Line 1:1:   Resolve error: unable to load resolver …
```
> Fix broken TS import

- src/components/MapView/DateSelector/index.tsx
Unfortunately, `react-datepicker` is timezone aware. However, we want the data to be displayed with the date it is actually stored at.
In order to achieve this goal, we `trick` the date-picker by adding the user timezone offset to dates, before passing them to the datepicker.
> Force date-picker to display "utc" dates

- src/components/MapView/Layers/BoundaryLayer/index.tsx
- src/config/layers.json
- src/config/types.ts
- src/context/layers/nso.ts
Fixes #93 
Addresses #29 
In particular:
- One data file with multiple data columns will only need to be imported once
- Names of the admin boundaries used in the tooltips can be configured easily in the admin_level_names of the admin boundary layer
- The name of the column with the admin code can be set in the config for both admin boundaries and data layers
> Flexible use of admin and data fields for admin level data

- src/config/layers.json
- src/config/types.ts
- src/context/layers/point_data.ts
- src/utils/server-utils.ts
Replaces #102
Test URL: http://prism-date-groundstation-test.surge.sh/
Possible Areas of Improvement:
- I made each layer have its own date fetching URL just in case dates start differing in the future.  ~This creates a small performance hit because we call the url 4 times instead of just once, but for now, doesn't create a huge performance hit. Make sure to confirm this!~ Fixed with cache
> Replace slow Date fetching with new Groundstation date API

- src/components/MapView/index.tsx
- src/utils/server-utils.ts
Closes #116
In the future, we could automatically select the latest compatible date between two or more layers and notify when that happens.
Note: it's not easy to test this pr anymore since WMS layers now support 21st. Will either have to manually replicate the issue or wait until there's a mismatch between groundstation and WMS layer dates
> Add new notification if date isn't available in layer

- src/components/MapView/index.tsx
- src/config/mozambique/layers.json
- src/config/mozambique/prism.json
- src/config/types.ts
- src/context/mapStateSlice/index.ts
- src/utils/server-utils.ts
This PR includes WFP ADAM layers into PRISM.
- Added field group on layers type schema.
- Included adam earthquake layer.
- Included adam tropical storms layers, displayed as single layer.
- Modified date parser to remove time values.
You can see demo of this PR here: http://homeless-giraffe.surge.sh/
> Adam integration with grouped layers

- src/components/MapView/DateSelector/index.tsx
- src/components/MapView/DateSelector/utils.ts
- src/components/MapView/index.tsx
This PR closes #153 
- Available dates are collected from an already defined function **findAvailableDayInMonth**
**UPDATE**
- This commit also includes the fetch of the closest date on a layer switch event. This is done, since there is a possibility that no available date might be found within the selected month.
Please check instance in http://homeless-giraffe.surge.sh
> Fetch first available date on a month switch event

- alerting/src/entities/alerts.entity.ts
- api-flask/app/database/alert_model.py
- src/components/MapView/AlertForm/__snapshots__/index.test.tsx.snap
- src/components/MapView/AlertForm/index.tsx
- src/components/MapView/Analyser/__snapshots__/index.test.tsx.snap
- src/components/MapView/Analyser/index.tsx
- src/config/index.ts
- src/context/analysisResultStateSlice.ts
- src/serviceWorker.tsx
- src/utils/analysis-utils.ts
- Re-order above / below thresholds
- transform missing min/max to undefined before sending the alert to the API
- Add "true" default to alert `active` field
> Use below/above language in the alert form. Add default boundaries file

- src/config/myanmar/layers.json
- src/config/myanmar/prism.json
- src/utils/server-utils.ts
The WMS version we were using is very out of date. 1.3.0 has been active since 2006. Tested locally for ODC OWS layers and GeoServer layers as well without issue.
This will close https://github.com/WFP-VAM/prism-frontend/issues/201
> update WMS version to 1.3.0

- api-flask/app/zonal_stats.py
This PR updates the Web feature service request for zonal statistics in the backend. Basically, the change includes time values of 00:00:00z. The issue was evident while executing the following query:
```
{
"geotiff_url": "https://odc.ovio.org/?service=WCS&request=GetCoverage&version=1.0.0&coverage=wp_pop_cicunadj&crs=EPSG%3A4326&bbox=92.2%2C9.7%2C101.2%2C28.5&width=1098&height=2304&format=GeoTIFF",
"zones_url": "https://prism-admin-boundaries.s3.us-east-2.amazonaws.com/mmr_admin_boundaries.json",
"group_by": "TS_PCODE",
"wfs_params": {
"url": "https://geonode.wfp.org/geoserver/ows",
"layer_name": "mmr_gdacs_buffers",
"time": "2015-07-29"
}
}
```
For more information about cql filters, please check: https://docs.geoserver.org/stable/en/user/filter/ecql_reference.html#filter-ecql-reference
> Modify cql_filter to allow 00:00:00 time values

- src/components/MapView/Layers/raster-utils.ts
- src/config/types.ts
- src/context/layers/wms.ts
This Pull request allows PRISM to execute WCS GetCoverage requests using versions 2.x. This option is enabled from the layer config file.
**How to test:** 
- As an example, modify wcsConfig for a layer in myanmar https://github.com/WFP-VAM/prism-frontend/blob/master/src/config/myanmar/layers.json#L438 and include **version** parameter to **2.0.0**.
- Verify within Network tab in your browser the geotiff url when executing Layer analysis
> Include wcs GetCoverage 2.x requests

- src/config/mozambique/layers.json
- src/config/myanmar/layers.json
- src/utils/server-utils.ts
Closes #212 
This PR modifies WMS GetFeatureInfo to version 1.1.1
It also modifies layer featureInfoProps to use **timestamp** field instead of **pub_date**
This branch has been deployed to http://demo-myanmar.surge.sh/
> Enforce WMS GetFeatureInfo version to 1.1.1

- src/components/MapView/Layers/AnalysisLayer/index.tsx
- src/components/MapView/Layers/ImpactLayer/index.tsx
- src/components/MapView/Layers/NSOLayer/index.tsx
- src/components/MapView/Layers/PointDataLayer/index.tsx
- src/components/MapView/Layers/WMSLayer/index.tsx
- src/components/MapView/Legends/index.tsx
- src/components/MapView/utils.ts
- src/context/analysisResultStateSlice.ts
- src/utils/analysis-utils.ts
Here is a list of minor issues and improvement added with regard to `exposure population analysis` table rendering
- Fixed `table` showing `index` number instead of `Group By` value
- Improved `table rendering` to be more dynamic and remove had-coded `Group By` and `label`
- Fixed `map` rendering to always show the `boundaries` layer before all other layers
> 🐛 Fix Exposure Population Analysis Minor issues

- src/context/analysisResultStateSlice.ts
This Pull Request closes #243 
On production environments, PRISM builds the admin boundaries URL for stats analysis using PATH parameter from layers config and server hostname. However, the regular expression removes only a single dot if the path is relative.
You can verify the PR here by running exposed population analysis and checking the zones_url within payload.
deployment site: http://demo-myanmar.surge.sh/
Also, please check this comment: https://github.com/WFP-VAM/prism-frontend/issues/243#issuecomment-907178795
> Modify regular expression to replace more than one dot

- api-flask/docker-compose.yml
Temporarily adding a generic prism-kobo account to the API
> Update docker-compose.yml with generic prism kobo user

- .circleci/config.yml
To avoid CI failures due to excess memory use such as here - https://app.circleci.com/pipelines/github/WFP-VAM/prism-frontend/1605/workflows/9867af11-2eb3-48e6-a453-c613568188fc/jobs/2895
We try to deactivate sourcemap.
> Deactivate sourcemap during ci frontend build

- api-flask/Makefile
- api-flask/README.md
- api-flask/app/kobo.py
- api-flask/app/main.py
- api-flask/app/tests/test_calculate.py
- api-flask/app/validation.py
- api-flask/app/zonal_stats.py
- api-flask/requirements.txt
When a user provides the parameter `intersect_comparison`, the API will calculate and return a new stat `intersect_percentage`.
The parameter accepts standard operators such as `<, >, <=, =, !=` in the form of `intersect_comparison=>=40`
> Add intersect option to the flask API

- src/components/MapView/Analyser/AnalysisTable/index.tsx
- src/muiTheme.tsx
Closes #357 
Deploy: http://prism-357.surge.sh/
Currently the analysis table returns the results from the API, not sure how they are sorted.
Added the option to sort results asc/desc by each column header.
> Add a sort option in 'run analysis' results

- src/components/DataDrawer/DataTable/DataTableRow/index.tsx
- src/components/MapView/Layers/AnalysisLayer/index.tsx
- src/components/MapView/Layers/ImpactLayer/index.tsx
- src/components/MapView/utils.ts
This closes #368 
Deploy: http://prism-368.surge.sh/
Remove rounding for tooltip values so that they match the values displayed in analysis table.
However, it can be ugly when the values have many decimal points, so should we round to 2dp instead?
> remove rounding for tooltip value

- src/components/MapView/Layers/BoundaryLayer/index.tsx
- src/context/analysisResultStateSlice.ts
- src/utils/name-utils.ts
This closes #356 
deploy: http://prism-issue-356.surge.sh/
modified the Name column in analysis table to include parent admin level's names. This also makes the name matches location name on tooltip
> Add admin parent name to analysis table

- src/components/MapView/Analyser/AnalysisTable/index.tsx
This PR fixes issue in #391.
Deploy link: http://prism-reset-pagination-onsort.surge.sh/
When the sorted column or sort direction is changed, table's pagination is reset to 0.
> Reset pagination on sort in analysis results

- src/components/MapView/utils.ts
The current regex would not work well for more than 3 decimals.
Using `toLocaleString` instead as commas is not the default in all countries. In prevision of #382
> Update number with commas in case we have more than 3 decimals

- api-flask/app/kobo.py
This quick fix resolves #446.
The error is because when kobo form return an empty lat/lon value and when the `gemo_field_type` is empty, the `parse_form_response` function cannot map the result into a dictionary of latitude and longitude points
This is a temporary fix, but looks like the process of parsing json data from kobo form at the moment is very complex/varies case by case. @ericboucher @wadhwamatic, do you have any idea how we can make it a bit more generalized? 
How to test:
1. run the API locally
2. Update kh_incident_report in `config\cambodia\layers.json` with:
```"form_name": "ទម្រង់ ឧបទ្ទវហេតុ"```
or
```"form_name": "NCDM_Live_Form"```
3. Change `data` and `date_url` into:
```
"data": "http://localhost/kobo/forms",
"date_url": "http://localhost/kobo/forms",
```
3. Run PRISM …
> KOBO - make geofield and group parsing more flexible

- api-flask/app/main.py
- api-flask/app/sample_requests.py
There was an issue with long sample request parameters. This PR ensures that they are considered as long strings and no 
"\n" gets inserted.
Before:
> Fix Swagger bug with long line in sample parameters

- src/config/cambodia/layers.json
- src/config/cuba/layers.json
- src/config/global/layers.json
- src/config/kyrgyzstan/layers.json
- src/config/mozambique/layers.json
- src/config/mozambique/prism.json
- src/config/myanmar/layers.json
- src/config/namibia/layers.json
- src/config/rbd/layers.json
- src/config/sierraleone/layers.json
- src/config/srilanka/layers.json
- src/config/tajikistan/layers.json
- src/config/zimbabwe/layers.json
This PR fixes missing WCS config information for the land surface temperature amplitude layer in all deployments. It also updates the legend labels and legend text
> Update the WCS config and labels for LST amplitude layer in all deployments

- .circleci/config.yml
This PR updates the Circle CI config to migrate from Ubuntu 16.04 to 20.04
https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/
> updated ubuntu version for circle CI

- src/config/mozambique/translation.json
- src/i18n.ts
This PR adds the missing 'pt' locale and implements it in the Mozambique translation configuration
> Add portuguese date locale

- src/components/DataDrawer/Chart/index.tsx
This PR fixes a bug where running an analysis followed by clicking on an layer with a chart associated with it causes an error.
> remove scale label parameter in chart config if x-axis is undefined

- src/components/MapView/Layers/PointDataLayer/index.tsx
- src/components/MapView/index.tsx
- src/components/NavBar/MenuSwitch/SwitchItem/index.tsx
- src/utils/url-utils.ts
- yarn.lock
This PR modifies PRISM to include multiple HazardLayers of different types (point, WMS) within the url.
**How to test:** Using Cambodia deployment
- Select a PointDataLayer, i.e. EWS 1294 river level data.
- Select a WMSLayer, 3-month rainfall aggregate (mm).
The url parameter **hazardlayerids** will have both layer ids. In case user selects another layer with the same type of a previously selected, PRISM will do an id replace.
closes #403
> Multiple layers url

- src/context/analysisResultStateSlice.ts
Sorry I forgot to check the "Run Analysis" in deployed URL for PR #474 (it has been merged now). The feature will not be working if it's served from a subfolder. This should fix it.
Deployed here: http://prism-sub-4.surge.sh/subfolder/build
> Fix for "Allow PRISM build to be served from a subfolder"

- src/config/index.ts
- src/config/types.ts
Fix #231 
Converting the union type to an intersection for supporting multiple countries.
```
type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
k: infer I,
) => void
? I
: never;
export type LayerKey = keyof UnionToIntersection<typeof rawLayers>;
```
Small Fix to typing of LayerKey #231
> Fix typing

- src/components/MapView/Layers/BoundaryDropdown.tsx
- src/config/index.ts
- src/config/types.ts
When we reselect admin level 1 in `Go To` feature we need only values from new admin level 1, but at the moment we added new admin level 1 to array and it's works wrong
Fix it by adding new props and now when we reselect admin level 1, we rewrite array using only selected data
now it works like that
https://user-images.githubusercontent.com/90055175/178262031-70bceffe-5113-4de8-8d09-7f2873436767.mov
> Enhance "go to" feature

- .gitignore
I updated .gitignore in order to exclude the following in any folder: node_modules, build, and coverage.  This is done in anticipation of creating a website folder per #413 .  For example, running `yarn install` in `prism-frontend/website` will create a node_modules folder at `prism-frontend/website/node_modules` and the current .gitignore would permit tracking of this new node_modules folder because it isn't at root.
Happy to answer any questions or discuss any concerns.
> issue-413: updated .gitignore

- src/utils/server-utils.ts
This PR fixes the following error on master when loading prism using an analysis url:
**How to test:** Using mozambique or any country deployment that contains adamts_buffers layer:
- Open the following link: http://localhost:3000/?analysisHazardLayerId=adamts_buffers&analysisAdminLevel=1&analysisStartDate=2020-08-02&analysisEndDate=2022-05-11&analysisStatistic=mean
> Fix bug with dates in URL in getPossibleDatesForLayer

- src/context/analysisResultStateSlice.ts
closes #585 
**How to test:**
- Set to run analysis.
- Select SPI 1 month as hazard layer.
- Select admin boundaries as baseline layer.
- Press run analysis
Verify that within the stats request in the network tab, the geotiff url has the time parameter, with the date specified.
> Fix conditional to include date parameter for geotiff url

- src/config/srilanka/layers.json
- src/config/srilanka/prism.json
This PR updates the demo version for PRISM Sri Lanka to make use of updated color ramps and styles from WFP's Humanitarian Data Cube. It also reorganizes prism.json to make use of layer grouping.
Surge deployment here:
https://prism-lka.surge.sh/
> Update color ramps & styles for climate layers; reorganize top navigation; COUNTRY=srilanka

- api/README.md
- api/app/zonal_stats.py
- api/docker-compose.deploy.yml
- src/config/index.ts
- src/config/kyrgyzstan/index.ts
- src/config/kyrgyzstan/layers.json
- src/config/kyrgyzstan/prism.json
This PR updates the demo version of PRISM Kyrgyzstan with new color ramps for climate layers from WFP's Humanitarian Data Cube. I also cleaned up the country level setup in index.ts in the config and kyrgyzstan folder
Deployed here: https://prism-kgz-demo.surge.sh/
> update Kyrgyzstan config color ramps; COUNTRY=kyrgyzstan

- src/config/mozambique/layers.json
- src/config/mozambique/prism.json
This PR adds missing charts for rainfall and rainfall anomaly layers (1-month and 3-month) generated from WFP's HDC API. I also cleaned up inconsistent layer ordering and names
Deployed here:
https://prism-moz.surge.sh/
> Additional chart configuration and layer clean-up; COUNTRY=mozambique

- src/config/cuba/layers.json
- src/config/cuba/prism.json
- src/config/mozambique/layers.json
- src/config/namibia/layers.json
- src/config/namibia/prism.json
- src/config/srilanka/layers.json
- src/config/srilanka/prism.json
- src/config/zimbabwe/layers.json
This PR updates 5 PRISM instances where WFP's Humanitarian Data Cube (HDC) provides 'blended' products which are based on global precipitation and temperature layers combined with local weather station data. 
The update addresses changes in how data layers are distributed through HDC, using a country-level layer and individual styles per date intervals. Note: this new approach in HDC changes how PRISM can access layers as WCS access is no longer included for all time intervals.
The modified instances include: Cuba, Mozambique, Namibia, Sri Lanka and Zimbabwe
The Mozambique deployment has been updated with this new configuration as an example: https://prism-moz.surge.sh/
> Configuration updates for HDC blended products

- common/src/base/test.ts
Fixes the following issue:
Basically an eslint rule from[ eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) called `prettier/prettier` automatically removes `: any` from `error: any`.  However, typescript doesn't like this.
The fix is to just disable the `prettier/prettier` eslint rule for the two lines with `error: any`.
> Prevent prettier from removing "error: any"

- frontend/src/components/MapView/Layers/raster-utils.ts
[This fixes issue [702].](https://github.com/WFP-VAM/prism-app/issues/702)
> Handle error if raster GeoTiff is not downloadable

- api/docker-compose.deploy.yml
- frontend/src/components/Common/SimpleDropdown/index.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/index.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
- frontend/src/utils/analysis-utils.ts
Ux revamp fix polygon analysis font style
and fix display of the table
> Ux revamp/fix polygon analysis style

- frontend/src/components/MapView/Download/index.tsx
- frontend/src/components/MapView/Download/reportDoc.tsx
This fixes issue [694](https://github.com/WFP-VAM/prism-app/issues/694).
Add `flood_extent` to layers which can generate flood reports. Also adds a condition for having the extra `Total` column
- Generate report for flood extent in Cambodia
- Check report generation works for previously existing cases
> Fix report would not generate for flood_extent COUNTRY=cambodia

- frontend/src/components/MapView/MapTooltip/index.tsx
This fixes issue [enter issue number]. Closes #712 
Popup has maximum width and height. Also set overflow as scroll.
- Set up prism instance for myanmar and modify ACLED layer to point to localhost.
- Select conflict fatalities layer.
- Select date 12 of january.
> Scrollable popup COUNTRY=myanmar

- frontend/src/components/MapView/DateSelector/index.tsx
- frontend/src/components/MapView/DateSelector/utils.ts
This fixes issue #741 
- select a layer with dates
- change the timezone in chrome - https://www.browserstack.com/guide/change-time-zone-in-chrome-for-testing
- reload the page and check that the ticks appear properly
> fix: Timezone bug with timeline item positioning

- frontend/src/components/DataViewer/index.tsx
- frontend/src/components/MapView/DateSelector/utils.ts
- frontend/src/components/MapView/Layers/BoundaryDropdown.tsx
- frontend/src/components/MapView/Layers/raster-utils.ts
- frontend/src/components/MapView/LeftPanel/ChartsPanel/ChartSection/index.tsx
- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
- frontend/src/components/NavBar/PrintImage/index.tsx
- frontend/src/config/cambodia/layers.json
- frontend/src/config/cambodia/prism.json
- frontend/src/config/mozambique/prism.json
- frontend/src/config/types.ts
- frontend/src/config/zimbabwe/prism.json
- frontend/src/context/datasetStateSlice.ts
- frontend/src/context/tooltipStateSlice.ts
- frontend/src/utils/admin-utils.ts
- frontend/src/utils/url-utils.ts
This PR adds national level charts provided that `countryAdmin0Id` is set in prism.json. (Actual configuration could evolve if we have the admin0 code available by other means)
This PR also improves the csv name generation adding the country name and all admin levels selected.
> Add national level charts; COUNTRY=cambodia

- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
Created "Clear All" button for clearing the selection UX flow in Charts Panel.
@ericboucher Please let me know if we need to remove also the `adminProperties` state variable when we clear the selection flow. As I tested the functionality seems to be working ok, without removing it from the state.
> Added "Clear All" Button for clearing charts selections

- frontend/src/components/Common/LoadingBlinkingDots/index.tsx
- frontend/src/components/Common/ReportDialog/index.tsx
- frontend/src/components/Common/ReportDialog/reportDoc.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
Added custom workaround to show loader in creating pdf reports of exposure analysis (currently waiting about 20 seconds for the report to be generated)
Select exposure analysis and click the create report button on the exposure analysis actions below in the sidebar.
> Add report doc loader

- frontend/src/components/DataDrawer/Chart/index.tsx
- frontend/src/components/MapView/LeftPanel/ChartsPanel/ChartSection/index.tsx
- frontend/src/config/cambodia/layers.json
- frontend/src/config/types.ts
- frontend/src/context/datasetStateSlice.ts
This branch takes into account the following assumptions:
- The `maxValue` `minValue` are added in the fields section of `layers.json` of `chart_data` collection.
- The codebase calculates the `max` and `min` values of multiple `maxValue` and `minValue` fields, if by mistake for example we configure `maxValue` of 200 in one field and `maxValue` of 300 in another field he codebase will keep the 300, the vise versa applies also in the min values.
- The `maxValues` and `minValues` are applied in the y-axis ticks as `suggestedMin` `suggestedMax`, this practically means that if a value is over the configured `maxValue`, or less than the configured `minValue` the ticks will be adjusted to facilitate those values.
@wadhwamatic I have added some `minValue` and `maxValue` and `pointRadius` in 10 …
> Added maxValue and minValue in charts configuration

- frontend/src/context/notificationStateSlice.ts
- frontend/src/utils/string-utils.ts
With this fix, we basically block the display of duplicate notifications by using a hash which is generated by the notification message.
This fixes issue [#814].
1. Select Cambodia
2. Enable layer X
3. Select a date that is out of range for a layer Y
4. Enable layer Y along with X
5. Expect to see a single notification saying there is no data for that date
https://github.com/WFP-VAM/prism-app/assets/24255041/a9a924c0-1bd0-47d7-831a-4c94f25af8c9
> Fix date warnings appear twice

- frontend/src/config/zimbabwe/layers.json
Add blended rainfall chart configurations for Zimbabwe
> Add blended rainfall chart config; COUNTRY=zimbabwe

- frontend/src/components/MapView/Map/index.tsx
This fixes map.getBounds problem when `REACT_APP_SHOW_MAP_INFO=true`
> Fixed map get bounds problem when showMapInfo is enabled

- frontend/src/components/Common/Chart/index.tsx
This fixes the problem with the time info in EWS-1294 charts. The problem was that the dates are actually in format `HH:mm`, and the moment could not parse it unless we had to explicitly define it. At some point this was working correctly with the exact same code I tried to revert to the previous code that was working and the problem seems to exist to the old code also. My guess is that at some point maybe an update to the package happened that does not allow us to parse hours without setting the format first. However this is a common pattern to parse the correct format based on this [stackoverflow](https://stackoverflow.com/questions/74189283/how-to-add-minutes-and-hours-to-a-string-in-momentjs), anyway this now fixes the problem and sets the correct parsing when we have `EWSconfig` or …
> Fixed time info in EWS-1294 charts; COUNTRY=cambodia

- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineLabel/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineLabel/index.test.tsx
- frontend/src/components/MapView/FoldButton/index.tsx
- frontend/src/components/MapView/LeftPanel/LeftPanelTabs/index.tsx
- frontend/src/components/MapView/LeftPanel/index.tsx
- frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/index.tsx
- frontend/src/components/MapView/index.tsx
- frontend/src/components/MapView/utils.ts
- frontend/src/utils/server-utils.ts
This branch deactivates the layers when no available dates are loaded with dispatching a message to info the user. Also this branch fixes a miscalculation of the active layers with the special case of Tropical Storms (Myanmar). Currently this applies to every country. The way to test this is to thow custom exceptions to the different functions that populate the dates to the `getLayersAvailableDates`, such us `localWMSGetLayerDates`, `localFetchCoverageLayerDays`, `getPointDataCoverage`. Those async functions are populating the dates remotely so if one of them throws an error we will not get the possible dates for some layers and we wil be able to test the feature of deactivating those layers that do not have available dates.
> Deactivate layers after failing to load dates

- frontend/package.json
- frontend/src/components/AuthModal/index.tsx
- frontend/src/components/MapView/Map/index.tsx
- frontend/src/components/MapView/index.tsx
This PR fixes a small mistake of falsly importing the `hidePanel` and `alertFormIsActive` from `map` property of `prism.json` file and not from the root which was initially their place.
> Fixed correct importing from app config for the hidePanel and alertFormIsActive properties

- frontend/src/config/srilanka/prism.json
This PR updates the Sri Lanka deployment to remove tropical storm layers and to make the default layer the blended precipitation layer from the Dept of Meteorology (DoM). We may activate the tropical storm layers again later but for now it's being removed to avoid any potential failures due to unavailability of the storm layers
> Remove tropical storm, set default layer to blended rainfall LKA

- frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap
- frontend/src/components/NavBar/index.tsx
Tiny fix to correct the broken link to github in the navbar which was returning a 404.
> Fix broken link in navbar

- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineLabel/index.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
This fixes issue https://github.com/WFP-VAM/prism-app/issues/890.
- check timeline
let me know which of the following we would prefer:
> Add background color on tick marks in the timeline UI

- frontend/src/components/NavBar/LanguageSelector/index.tsx
- frontend/src/config/index.ts
- frontend/src/config/indonesia/index.ts
- frontend/src/config/mozambique/prism.json
This fixes issue https://github.com/WFP-VAM/prism-app/issues/726.
- edit `prism.json`'s `defaultLanguage` field.
- start the app and check the default language selected
> Add defaultLanguage configuration option

- frontend/src/config/cambodia/layers.json
- frontend/src/config/cambodia/prism.json
Configuration updates for Cambodia based on input from WFP Cambodia office:
1. Make Khmer the default language
2. Extend the range of values for flood impact report symbology
> Make Khmer default lang & update flood report legend; COUNTRY=cambodia

- frontend/src/utils/server-utils.ts
In an effort to speed up the app for RBD, we only generate validity periods for dates that are less than 5 years old
> Only generate validity periods for dates less than 5 years old

- frontend/src/components/MapView/LeftPanel/ChartsPanel/LocationSelector/index.tsx
- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
The admin1 dropdown was not populating properly for admin 1 in single country deployments
> Hotfix charts dropdown issue

- frontend/src/config/myanmar/layers.json
- frontend/src/config/myanmar/prism.json
This fixes missing admin codes for charts in adm3 boundary file, and reconfigure ADAM layers
Charts:
- load 10-day rainfall layer
- click on an admin area
- select a chart from the tooltip
ADAM layers:
- load a tropical storm layer
- run exposure analysis on the results
> add chart fields to admin 3 and update storm layers; COUNTRY=myanmar

- frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx
- frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/index.tsx
- frontend/src/components/MapView/Legends/LegendItem/index.tsx
- frontend/src/components/MapView/Legends/layerContentPreview.tsx
This fixes #1003 by pointing to active layer in group layers.
> Point to active layer for geotiff downloads in group layers

- api/app/geotiff_from_stac_api.py
- api/app/main.py
- api/app/models.py
- frontend/src/components/MapView/Layers/raster-utils.ts
- frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx
- frontend/src/config/zimbabwe/layers.json
This tentatively fixes #1005. By adding a "band" additional_query_parameter.
Unfortunately it doesn't seem super easy to infer the band name from the style name so I added an additional parameter for now. This won't work as is since it's not deployed to the API but you can give it a try locally.
The band info is now added to the filename if it is not simply "band".
> Optionally pass band info for STAC download; COUNTRY=zimbabwe

- frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
Make it easier to scroll in the analysis panel on smaller screens.
> Add scroll to analysis panel

- frontend/src/components/Common/HashText/index.tsx
- frontend/src/components/MapView/LeftPanel/layersPanel/index.tsx
- frontend/src/components/MapView/Map/index.tsx
- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
This fixes #1017 and #1021.
- Hash version now stays below the menu items. Hash version is now logged to the console as well.
- layer ordering should be fixed for raster data stacked in-between admin boundaries
> Frontend bug fixes - hash position and layer opacity; COUNTRY=zimbabwe

- api/app/main.py
This PR tells browsers to cache results of the `/kobo/dates` api call.
For Cambodia, there are 3 such calls when loading the app, 2 of which take 2-4s each. Caching improves overall load time for the page. I've set the caching period to 24h, under the assumption that the dates shouldn't change much over that period of time.
Other countries don't seem to be affected by this change.
> Cache kobo dates results in the browser

- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
This fixes #1026 and #992.
It shows the full country name instead of a country code above charts, and in the CSV filenames. 
> Use country names above charts and in csv filenames; COUNTRY=rbd

- frontend/package.json
- frontend/src/components/MapView/Layers/BoundaryLayer/index.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/ExposureAnalysisTable/index.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/index.tsx
- frontend/src/components/MapView/MapTooltip/PopupCharts/PopupAnalysisCharts.tsx
- frontend/src/components/MapView/MapTooltip/PopupCharts/index.tsx
- frontend/src/components/MapView/MapTooltip/PopupContent.tsx
- frontend/src/components/MapView/MapTooltip/index.tsx
- frontend/src/context/analysisResultStateSlice.ts
- frontend/src/context/tooltipStateSlice.ts
- frontend/yarn.lock
This is a hotfix for a small bug in popup chart whereby the data sent to the chart was never the correct one.
To reproduce the bug:
- country=cambodia (but any other will show the bug)
- activate a data layer, for instance "rainfall amount"
- click any are of the map to bring up the popup, and load a chart
- save CSV data for easier comparison (or just a good look at the shape of the chart will do)
- click some other part of the map. the chart reloads the same data
(this can be confirmed by looking at the network requests which all relate to the same boundary code)
This PR fixes this, so that data is fetched for the area that was indeed clicked.
Same as above, but the network requests are now different for each click, and admin codes can be confirmed with the json data.
Test your changes …
> Select correct boundary area to request data for

- frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
> Analysis - hide extended validity dates and only show actual query dates; COUNTRY=rbd

- frontend/src/components/MapView/LeftPanel/ChartsPanel/ChartSection/index.tsx
- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
This fixes #1015 .
Make charts have the same scale when comparing locations or periods.
- navigate to chats panel
- select compare locations or periods
- verify that both charts have the same y scale
> Charts - unify scale when comparing

- frontend/src/components/MapView/MapTooltip/PointDataChart/PopupPointDataChart.tsx
- frontend/src/components/MapView/MapTooltip/index.tsx
This fixes #1055
Use download icons for EWS charts.
This makes the experience across charts more consistent.
There is more data in the CSV now (it includes the alert thresholds) but the date field only show the time. In addition, the CSV filename is a bit different and only includes the title. I don't think it's an issue but let us know if you would like any of this to change @wadhwamatic 
> Use download icons for EWS charts; COUNTRY=cambodia

- common/src/utils/time.ts
- frontend/package.json
- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineItem/index.tsx
- frontend/src/context/store.ts
- frontend/src/utils/date-utils.test.ts
- frontend/src/utils/date-utils.ts
- frontend/src/utils/layers-utils.tsx
- frontend/src/utils/server-utils.test.ts
- frontend/src/utils/server-utils.ts
This fixes (partially) #467 .
I used firefox profiler to identify CPU heavy functions in the code when loading the app for RBD, and tried to speed up the most time consuming ones. Speedups range from 25% up to 10-20x.
I suggest reviewing the PR commit by commit, as each of them does one thing, it will make more sense than trying to look at everything together.
> Speed up various date processing functions; COUNTRY=rbd

- frontend/src/components/MapView/Layers/AdminLevelDataLayer/index.tsx
- frontend/src/components/MapView/Layers/AnalysisLayer/index.tsx
- frontend/src/components/MapView/Layers/BoundaryLayer/index.tsx
- frontend/src/components/MapView/Layers/ImpactLayer/index.tsx
- frontend/src/components/MapView/Layers/PointDataLayer/index.tsx
- frontend/src/components/MapView/Layers/layer-utils.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/ExposureAnalysisTable/index.tsx
- frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/index.tsx
- frontend/src/components/MapView/Map/index.tsx
- frontend/src/components/MapView/useMapOnClick.ts
- frontend/src/utils/map-utils.ts
changes the way we register layer to use `map.on`. This way `map.fire` triggers onclick events.
note that the event produced by `map.fire`, returns coordinates in an array instead of an object
> Register onclick with map.on

- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineItem/index.tsx
- frontend/src/components/MapView/DateSelector/index.tsx
This fixes #1065 and a few other issues with the date picker.
The date selector and the date arrows where blocking clicks on the date picker.
@laurentS let me know if you think my changes make sense.
The logic in this file is way too complicated imho and might need a revamp...
> Fix date shift issue; COUNTRY=rbd

- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
> Fix comparison period chart date title

- frontend/src/components/MapView/Layers/AdminLevelDataLayer/index.tsx
- frontend/src/components/MapView/Legends/handleChangeOpacity.ts
- frontend/src/components/NavBar/PrintImage/image.tsx
This PR simplifies the logic around the opacity setting uncovered in #1074 by following the tips from https://github.com/maplibre/maplibre-gl-js/issues/3373.
> Simplify opacity logic in print; COUNTRY=rbd

- frontend/src/components/MapView/LeftPanel/index.tsx
- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
/claim #1012 
This fixes #1012 
Source of the bug comes from using makeStyles to style MUI drawer's paper.  Looks like by MUI version 4.12 Drawer was already taking PaperProps as a prop, which accepts all props drilled down to the paper component.
See [stackoverflow](https://stackoverflow.com/a/70039483), [stackoverflow MUI 5](https://stackoverflow.com/questions/69494901/how-to-style-the-paper-of-a-drawer-in-mui) and [MUI documentation](https://mui.com/material-ui/api/drawer/)
[Loom video ](https://www.loom.com/share/b77da639009d4eb3aefbe849b9c97152?sid=9572c1f4-03a9-4588-89cd-62d62c4904ee)
> fix(frontend): apply styles to drawer's paper

- frontend/src/config/mozambique/layers.json
- frontend/src/config/zimbabwe/layers.json
- frontend/src/config/zimbabwe/prism.json
Reorder layers in Zimbabwe and Mozambique so that the sequence in the charts feature shows blended rainfall products at all aggregations, then CHIRPS.
Add forecast anomaly layer to Zimbabwe.
> re-order blended rainfall layers for chart feature; add forecast anomaly; COUNTRY=zimbabwe

- frontend/src/components/MapView/DateSelector/index.tsx
- frontend/src/components/MapView/DateSelector/utils.ts
This fixes a bug, where in some cases the date picker would not update the selected date, when clicking it
The bug was caused by the user timezone offset we would add, causing timestamps from the same date not to be equal for few hours and as a result the same date being picked from `findDateIndex`.
Since we now set UTC hours to 12, for every date, we should no longer need the users offset to correctly display the date.
> Fix datepicker would not update dates

- frontend/public/data/mozambique/anticipatory-action/SPI_probabilities_season_triggers.csv
- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/index.tsx
- frontend/src/context/anticipatoryActionStateSlice/index.ts
- frontend/src/context/anticipatoryActionStateSlice/types.ts
- frontend/src/context/anticipatoryActionStateSlice/utils.ts
Districts can be vulnerable or not. Vulnerable districts use Emergency Triggers while others use standard General Triggers.
This replaces the index dropdown with this info.
@echaidemenos I implemented this quickly for now but we might want to rethink this and augment the monitoredDistrict info instead to be `{name, vulnerability}[]` wdyt?
Can you have a quick look at the spacing? it seems off now but I'm not sure why
> AA - District level vulnerability info

- api/app/report.py
- frontend/src/components/MapView/Map/index.tsx
Fixes an issue where the map image would not appear in the flood report
- Use country cambodia
- Activate layer Flood / Flood Monitoring / Flood extent and run analysis
- Click on "Preview Report (slow)" button and verify the report
> Fix map image would not show in report; COUNTRY=cambodia 

- frontend/src/components/NavBar/PrintImage/image.tsx
This fixes #1196 
- Go top print preview
- Try editing the title text, pause for 2-3 seconds and start typing again
- notice the focus is not lost
> Fix loss of focus when editing text in print preview

- frontend/src/components/MapView/LeftPanel/index.tsx
- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
Fixes a bug where charts panel would appear like this
> Fix panel size

- frontend/src/components/NavBar/PrintImage/__snapshots__/index.test.tsx.snap
- frontend/src/components/NavBar/PrintImage/image.tsx
- frontend/src/config/shared/prism.json
This fixes #1208 and #1222.
This PR adds a footer with the publication and layer selection dates. Not editable for now but translatable.
This also re-adds the default footer text in the shared prism.json, making it easy to override. Eventually, we should have a reasonable set of defaults in the `shared/prism.json` showing users what settings they can easily configure and toggle.
> Add publication and layer selection dates in print

- frontend/src/components/NavBar/PrintImage/__snapshots__/index.test.tsx.snap
- frontend/src/components/NavBar/PrintImage/image.tsx
A quick fix for the footer overlapping with the scale bar
before
after
> Fix footer overlapping scale bar

- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/ActionsModal/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/ActionsModal/actions.tsx
Add AA icons for the Normal category.
> Add AA icons for the Normal category; COUNTRY=zimbabwe

- frontend/src/components/MapView/Legends/LegendImpactResult/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/Legends/LegendImpactResult/index.tsx
- frontend/src/components/MapView/Legends/LegendItem/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/Legends/LegendItem/index.tsx
- frontend/src/components/MapView/Legends/LegendMarkdown.tsx
I noticed during my work on #1173 that the markdown wasn't working on the Legend panel for analysis results. This fixes that issue.
- Creating Legend Markdown component
- Applying in both LegendItem and LegendImpactResult
| Before | After |
| - | - |
| <img width="1137" alt="Screenshot 2024-07-03 at 12 27 06 PM" src="https://github.com/WFP-VAM/prism-app/assets/8203830/4a2a5884-df33-4461-8860-20b863805abf"> | <img width="1142" alt="Screenshot 2024-07-03 at 12 25 50 PM" src="https://github.com/WFP-VAM/prism-app/assets/8203830/a29d7a4e-df8a-4102-8899-bf9210d2b39d"> |
> Supporting Legend Markdown for analysis results; COUNTRY=rbd

- frontend/src/i18n.ts
Running the app in English results in every translation key reported as missing (because there are no english translations provided). This suppresses the unhelpful warning for English.
> Only log missing key if language not English

- frontend/src/components/MapView/LeftPanel/utils.ts
This fixes #1324 by returning layer with group from formatLayersCategories regardless of whether layer is frozen.
Bug:
https://www.loom.com/share/9836aea706db463f958c47928f092ab2?sid=30bd8f75-206e-4ce2-b470-0489a168e8e6
Fix: 
https://www.loom.com/share/5d8eaacc94b2426f922e3f3f58c19d47?sid=efb91ecc-a4f2-44eb-bb1e-c5a10e85f14d
> Bugfix: Dropdown layer selection remains after selection; COUNTRY=jordan

- frontend/src/context/anticipatoryActionStateSlice/utils.ts
- frontend/src/utils/layers-utils.tsx
This fixes an issue where the prevMax was not getting properly reset when going through the AA data and entering a new season.
@gislawill this also fixes a bug with the layer removal process that was trying to remove "undefined" layers when loading AA from URL. Eg. loading http://localhost:3000/?hazardLayerIds=anticipatory_action&date=2024-08-14. 
> Fix season prevMax reset for AA; COUNTRY=zimbabwe

- frontend/src/components/MapView/LeftPanel/layersPanel/MenuItem/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx
This addresses #1336 by adding support for CSV + GeoJSON files of CDI data.
https://www.loom.com/share/a3c8cc4955a44112a0b3ed4983bbdf7b
> Adding capability for CSV + GeoJSON download of composite data; COUNTRY=jordan

- frontend/src/config/shared/translation/english.json
This fixes #1364.
There was a mistake in translation file for `date_locale` that was causing the bug.
> Fix chart comparison crash

- api/app/zonal_stats.py
This fixes #1376. The code needs to be able to count `nodata` areas as well to calculate exposure.
> Fix failing area exposed

- frontend/src/components/MapView/Layers/CompositeLayer/index.tsx
- frontend/src/config/jordan/layers.json
- frontend/src/config/jordan/prism.json
- frontend/src/config/types.ts
- frontend/src/context/layers/composite_data.ts
This PR adds the aggregation feature which was developed in https://github.com/WFP-VAM/prism-app/pull/1326 but not yet merged
> Add CDI (composite layer) aggregation; COUNTRY=jordan

- .github/workflows/api.yml
- frontend/src/components/Common/AnticipatoryAction/icons.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/AAStormTimelineItem/index.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/hooks.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/types.ts
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AAStormLegend/index.tsx
- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/useAnticipatoryAction.ts
- frontend/src/context/anticipatoryAction/AAStormStateSlice/index.ts
- frontend/src/context/anticipatoryAction/AAStormStateSlice/types.ts
- frontend/src/context/anticipatoryAction/config.ts
- clean anticipatory action state
- handle TODO - create a file to make the icons easier to access
- handle // TODO - setAAFilters is mostly used for the viewType. Maybe rename and make sure it's used for the viewType only?
> remove useless aa storm state items

- frontend/package.json
- frontend/src/components/MapView/DateSelector/TimelineItems/AAStormTooltipContent/index.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/TimelineLabel/index.test.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/AAStormLandfallPopup/PopupContent/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/utils.test.ts
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/utils.ts
- frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AnticipatoryActionStormPanel/index.tsx
- frontend/src/i18n.ts
- frontend/yarn.lock
- display landfall detail popup using mozambic time
- display date popups using mozambic time
- display timeline popup in UTC
- display panel report time in UTC
> Aa storm feature/use local time

- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
The error occurred because some layers were being added before the layer "aa-storm-wind-points-layer", which had not yet been defined.
Error: Cannot add layer "aa-storm-wind-points-line-future" before non-existing layer "aa-storm-wind-points-layer".
This was fixed by ensuring that all referenced layers, such as "aa-storm-wind-points-layer", are declared before using them in the beforeId property for other layers.
> Fix errors when loading storm layer

- frontend/src/config/jordan/layers.json
- frontend/src/config/jordan/prism.json
- frontend/src/config/shared/legends.json
This fixes https://github.com/WFP-VAM/prism-app/issues/1425
1. Fixes an error in the configuration of input layers for CDI (invert used string instead of boolean)
2. Adds CDI v3 (water-based) which matches what's being used across Africa
> Fix CDI invert error & add water-based version; COUNTRY=jordan

- frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
It fixes the display of the popup showing details about the landfall. This popups appears only when clicking on the windpoint corresponding to the landfall time. It is also marked with a permanent popup showing 'LF....' 
> fix display of the landfall details popup

- frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
it fixes #1413 
- Go to the charts module
- Toggle on compare locations
- Choose any two locations for example: 
- location1, admin1 : cabo Delgado
- location1, admin2: ancuabe
- location2, admin1: Gaza
- location2, admin2: Bilene
- select data to plot, for example "10-day NVDI (MODIS)"
- Click download CSV in the top right of the chart in location 2
- assert that the filename is mozambique_gaza_bilene_10_day_ndvi_modis.csv
- Click download image in the top right of the chart in location 2
- assert that the filename is mozambique_gaza_bilene_10_day_ndvi_modis.png
You can do the same for the chart corresponding to location 1
- Click download CSV in the top right of the chart
- assert that the filename is mozambique_cabo_delgado_ancuabe_10_day_ndvi_modis.csv
- Click download image in the …
> Fix the filename of the second chart for downloading  

- frontend/src/components/MapView/DateSelector/TimelineItems/AAStormTooltipContent/index.tsx
- frontend/src/components/MapView/DateSelector/TimelineItems/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
- frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
Improve tooltip behavior by:
- using colors to display the status of each hour
- always display storm name even when there is only one
- add tooltip "enter" and "leave" delays to make it a bit easier to move to the tooltip before it disappears
> Improve tooltip design

- frontend/src/config/afghanistan/prism.json
- frontend/src/config/bhutan/prism.json
- frontend/src/config/cambodia/prism.json
- frontend/src/config/cameroon/prism.json
- frontend/src/config/colombia/prism.json
- frontend/src/config/cuba/prism.json
- frontend/src/config/ecuador/prism.json
- frontend/src/config/global/prism.json
- frontend/src/config/haiti/prism.json
- frontend/src/config/indonesia/prism.json
- frontend/src/config/jordan/prism.json
- frontend/src/config/kyrgyzstan/prism.json
- frontend/src/config/mozambique/prism.json
- frontend/src/config/myanmar/prism.json
- frontend/src/config/namibia/prism.json
- frontend/src/config/nepal/prism.json
- frontend/src/config/nigeria/prism.json
- frontend/src/config/rbd/prism.json
- frontend/src/config/shared/layers.json
- frontend/src/config/sierraleone/prism.json
- frontend/src/config/somalia/prism.json
- frontend/src/config/southsudan/prism.json
- frontend/src/config/srilanka/prism.json
- frontend/src/config/sudan/prism.json
- frontend/src/config/tajikistan/prism.json
- frontend/src/config/tanzania/prism.json
- frontend/src/config/zimbabwe/prism.json
This PR is a layer configuration change that adds spi 2-month to the shared layers.json file, and then adds the layer to layers.json for all active countries
> add spi 2-month for active countries; COUNTRY=mozambique

- frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
- frontend/src/config/cambodia/prism.json
- frontend/src/config/mozambique/prism.json
- frontend/src/config/rbd/prism.json
This reverts the prism.json updates in https://github.com/WFP-VAM/prism-app/pull/1332 that result Google Floods being accessible in Cambodia, Mozambique, and RBD deployments.
> Reverting google floods in Deployments; COUNTRY=mozambique

- alerting/cron_aa_storm_alert_run.sh
- alerting/cron_alert_run.sh
- api/README.md
This fixes an issue with the alerting docker leaving a bunch of orphan volumes and racking up all the available space on the server.
> Fix monster docker volumes - Tentatively add --rm flag

- frontend/.eslintrc.cjs
- frontend/src/components/App/index.tsx
- frontend/src/components/DashboardView/index.tsx
- frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap
- frontend/src/components/NavBar/index.tsx
- frontend/src/config/mozambique/prism.json
- frontend/src/config/types.ts
- frontend/src/config/utils.ts
- frontend/src/context/leftPanelStateSlice.ts
This sets up some foundational pieces of the dashboard/reports* feature. Highlights:
- Add `ConfiguredReport` and associated types
- Display Dashboard in nav bar if it exists for a given deployment config
- Allow a user to choose a configured report
<details><summary>*<strong>Dashboard context</strong></summary>
<p>
Just a bit of background on the dashboard/reports feature…
This is the very beginning phase of a larger effort to provide configurable reports to Prism users. Deployment configs can specify a “dashboard” comprising a map and one or more content blocks (e.g. text, a chart, or a table). This inaugural PR is to specify the overall structure of the config shape and initialize a navigable placeholder dashboard.
</p>
</details> 
I’ve left a few inline comments throughout to provide …
> Dashboard shell

- frontend/src/components/MapView/MapTooltip/index.tsx
This fixes a new issue introuded in #1328 for RBD CH tables
@gislawill can you check that it doesn't impact the issue you were having at the time? https://github.com/WFP-VAM/prism-app/pull/1328/files#r1838419804
> Fix RBD CH tooltip table size

- frontend/src/components/DashboardView/DashboardPreview.tsx
- frontend/src/components/DashboardView/TextBlock.tsx
- frontend/src/components/DashboardView/index.tsx
Implements a basic preview mode for Dashboards. You should be able to select **Preview** in the new toolbar at the bottom of the main Dashboard view. This will display a modal with read-only versions of the title and text block components.
TextBlock will render Markdown content — we can adjust which elements are allowed and how they’re styled as needed.
* I had trouble finding a way within the MUI APIs to render the “Back to Edit” and “Publish” buttons above the modal as shown in designs. Willing to keep playing around with it but didn’t it to be come too big of a time sink — any guidance or suggestions appreciated
* Publish button in the toolbar is not in scope for this PR
> Initial preview mode

- .github/workflows/frontend.yml
- api/app/report.py
- common/package.json
- frontend/.eslintrc.cjs
- frontend/cypress.config.ts
- frontend/cypress/e2e/all_countries.cy.ts
- frontend/cypress/e2e/cambodia.cy.ts
- frontend/cypress/e2e/mozambique.cy.ts
- frontend/cypress/e2e/rbd.cy.ts
- frontend/cypress/support/commands.ts
- frontend/cypress/support/e2e.ts
- frontend/package.json
- frontend/src/components/MapView/DateSelector/__snapshots__/index.test.tsx.snap
- frontend/src/components/MapView/DateSelector/index.tsx
- frontend/src/components/NavBar/LanguageSelector/index.tsx
- frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap
- frontend/yarn.lock
This PR supersedes #1522 sets up e2e testing with cypress.
It reuses the current state of the original cypress PR that was based on a long branch of unrelated changes.
> Setup e2e testing with cypress on master
