.circleci/config.yml
.firebaserc
package.json
src/components/MapView/Boundaries/index.tsx
src/components/NavBar/__snapshots__/index.test.tsx.snap
src/components/NavBar/index.tsx

@mamadOuologuem I had to make small changes in the firebase config and deploy scripts
Let's make sure this is working on your end.

Quick fixes for firebase and scripts

---

package.json
src/components/App/__snapshots__/index.test.tsx.snap
src/components/App/index.tsx
yarn.lock

🐛 Fix NotFound page in app router

---

src/config/layers.json
src/config/prism.json

Note - It is ok if Dzud maps fetching data from the geoserver are not working at the moment

Add additionali impact layers

---

src/context/mapStateSlice.ts

Only allow one layer of each type at a time

---

src/components/MapView/Boundaries/index.tsx
src/components/MapView/Layers/GroundstationLayer/index.tsx
src/components/MapView/Layers/ImpactLayer/index.tsx
src/components/MapView/Layers/NSOLayer/index.tsx
src/components/MapView/Layers/WMSLayer/index.tsx
src/components/MapView/index.tsx

It seems to work locally but I am not sure how to best test this. Ideas @bencpeters ?

Order layers below admin boundaries

---

public/data/tables/NSO_Bale_Hay_Price_Monthly_Avg2.csv
src/components/DataDrawer/Chart/index.tsx
src/config/prism.json
src/config/tables.json
src/config/types.ts

Adding line charts and the ability to "transpose" datasets

Add line charts

---

src/components/DataDrawer/Chart/index.tsx

Add a borderColor to make sure that tooltips appear for stacked lined charts

Fix line charts

---

package.json
yarn.lock

Fixes https://github.com/oviohub/prism-frontend/issues/77
Ensure it works for every other environment you use just in case!

Add cross-env for Windows support

---

src/components/MapView/index.tsx
src/utils/server-utils.ts

merge date notification into mongolia production

Add new notification if date isn't available in layer (#117)

---

api-flask/app/caching.py
api-flask/app/database/alert_database.py
api-flask/app/errors.py
api-flask/app/main.py
api-flask/app/zonal_stats.py

- Make sure that everything has a type (avoid Any type, wherever possible)
- Add error handling to send json errors instead of html pages
- Use the built-in exception classes for error responses
- Clean up demo api test urls
- Add missing input validation on /alerts/<id>

Flask api enhancements

---

src/components/MapView/Layers/AnalysisLayer/index.tsx
src/components/MapView/Legends/index.tsx
src/config/mozambique/layers.json
src/config/myanmar/layers.json
src/config/types.ts
src/context/analysisResultStateSlice.ts
src/utils/analysis-utils.ts

Closes #219 
This PR enables the value update given scale and offset parameters for each feature returned from the API. These parameters are set within the wcsConfig variable within the layers configuration file.

scale statistic value given parameters

---

src/config/mozambique/layers.json

See https://github.com/WFP-VAM/prism-frontend/issues/250

fix mozambique layers based on OWS updates

---

src/components/MapView/Legends/index.tsx
src/config/types.ts

Allow custom label on Legend

---

.circleci/config.yml
src/utils/analysis-utils.ts

Filter out nullish values during an analysis.
This way, when running flood analysis, we only get matching admin boundaries when the boundary has been affected:

Filter out nullish values during analysis

---

src/components/MapView/Legends/index.tsx

Better function name as suggested on #327 
Sorry I missed this one earlier, feel free to edit or replace my PR as required

Rename legendItemLabel to getLegendItemLabel

---

src/context/analysisResultStateSlice.ts

Select latest admin level for exposed population analysis

---

src/components/App/__snapshots__/index.test.tsx.snap
src/components/App/index.tsx

Include navbar within auth wrapper component

---

src/config/mozambique/layers.json
src/config/namibia/layers.json
src/config/srilanka/layers.json

this fixes a few configuration issues i noticed today

fix rainfall anomaly config in moz, namibia, sri lanka

---

src/components/MapView/index.tsx

Maintain map position when loading a new layer

---

api-flask/README.md
api-flask/docker-compose.deploy.yml
api-flask/docker-compose.yml

Remove KOBO password from dc file and load from environment variable instead

Remove kobo password from docker-compose

---

scripts/truncate_precision.sh

after truncating precision, delete the backup files.

Delete backup files after truncating precision

---

src/components/DataViewer/index.tsx

Include translation for chart title

---

src/components/MapView/Analyser/index.tsx
src/config/mozambique/translation.json
src/utils/constants.ts
src/utils/data-utils.ts
src/utils/types.ts
src/utils/url-utils.ts

This PR closes #434 
Deployed at : http://prism-434.surge.sh/
To test this PR:
1. REACT_APP_COUNTRY=cambodia yarn start (or pick any other country) or go to http://prism-434.surge.sh/
2. Run analysis: 10-day rainfall + IDPoor, any threshold/date
3. Click 'run analysis', wait for the result
4. Click on "Share analysis", the URL will be copied to clipboard.
5. Open a new tab and paste the URL to the new tab. You can see that the analysis table is prefilled with the same settings. Click "Run analysis" and wait for the result. The result in the new tab should be the same as the old tab,

Generate url for analysis and allow users to copy/share

---

src/components/MapView/Layers/PointDataLayer/index.tsx
src/components/MapView/index.tsx
src/components/NavBar/MenuSwitch/SwitchItem/index.tsx
src/utils/url-utils.ts

Reverts WFP-VAM/prism-frontend#490

Revert "Multiple layers url"

---

public/data/cambodia/flood-hazard-index.json
src/config/cambodia/layers.json
src/config/cambodia/prism.json

This PR adds a flood hazard index for commune in Cambodia as an admin level layer.

Add flood hazard index for Cambodia

---

api-flask/Makefile
api-flask/requirements.txt

Add black and isort to the API's docker requirements

Add black and isort to docker requirements

---

config-overrides.js
package.json
yarn.lock

Rewrite build script for deleting unused countries from build
Script get selected script from `env` - `REACT_APP_COUNTRY` and then delete other countries, if country not providing do nothing

Remove other countries from build folder

---

api-flask/Dockerfile
api-flask/docker-compose.deploy.yml

Fixing the deployment docker-compose file following the switch to FastAPI

Hotfix - API docker config for deployment

---

src/components/MapView/Download/report.tsx
src/components/MapView/Download/reportDoc.tsx

This PR:
- Fixes warning `Image should receive either a "src" or "source" prop`

TypeError bug fix in ReportDoc

---

src/utils/zonal-utils.ts

fix https://github.com/WFP-VAM/prism-app/issues/580

Change zonal script link to use https

---

src/config/southsudan/layers.json

Quick fix for the heavy rainfall layer configuration

fix heavy rain layer config; COUNTRY=southsudan

---

src/config/global/index.ts
src/config/global/layers.json
src/config/global/prism.json
src/config/index.ts

This PR updates color ramps and the 'country' setup .ts files for a global deployment of PRISM.
Demo version deployed here:
https://demo-prism-global.surge.sh/

update color ramps and 'country' setup; COUNTRY=global

---

src/config/cambodia/layers.json

This PR configures changes to the Kobo form fields used in the flood_report layer

Update kobo form fields for flood report; COUNTRY=cambodia

---

src/components/MapView/Download/reportDoc.tsx

this PR resolves https://github.com/WFP-VAM/prism-app/issues/590

Fix PDF downloading on windows/firefox

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

issue https://github.com/WFP-VAM/prism-app/issues/654
This PR adds templates for issues and feature requests

Add issue template forms for bugs and feature requests

---

.github/workflows/build.yml

This PR adds a CD for master.
It creates 3 deployments on push to master:
- Cambodia https://prism-master-cambodia.surge.sh/
- Mozambique https://prism-master-mozambique.surge.sh/
- RBD https://prism-master-rbd.surge.sh/
Those deployments are not triggered by a pull request:

Automated deployments from the master branch

---

frontend/public/data/cambodia/about.md

[ ] Related issue: https://github.com/WFP-VAM/prism-app/issues/658 
[ ] How to test the feature:
[ ] Screenshot/video of feature:

Update about.md; country=cambodia

---

.github/workflows/build.yml

Add Sentry to deployments of the master branch during CI.

Add Sentry to CI master deployments

---

frontend/src/components/MapView/LeftPanel/LeftPanelTabs.tsx
frontend/src/components/MapView/LeftPanel/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/index.tsx

Ux revamp: add side bar and tabs

---

frontend/src/components/MapView/AlertForm/index.tsx
frontend/src/config/cambodia/prism.json

Fix alert success message

---

README.md
frontend/src/components/DataDrawer/Chart/index.tsx
frontend/src/components/MapView/DateSelector/index.tsx
frontend/src/components/MapView/FoldButton/index.tsx
frontend/src/components/MapView/Layers/BoundaryDropdown.tsx
frontend/src/components/MapView/Layers/BoundaryLayer/index.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
frontend/src/components/MapView/LeftPanel/ChartsPanel/ChartSection/index.tsx
frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
frontend/src/components/MapView/LeftPanel/LeftPanelTabs.tsx
frontend/src/components/MapView/LeftPanel/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/index.tsx
frontend/src/config/mozambique/prism.json
frontend/src/config/types.ts
frontend/src/config/utils.ts

Ux revamp add the chart tab

---

common/src/base/test.ts
frontend/src/components/MapView/FoldButton/index.tsx
frontend/src/components/MapView/Layers/BoundaryDropdown.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/index.tsx

Ux revamp/style fold button

---

frontend/src/components/NavBar/About/index.tsx
frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap

This fixes issue [enter issue number]. #703
- Load prism mongolia instance
- switch language and verify the About link language changes
http://g.recordit.co/jiIaI1AaE2.gif

Fix about translation mongolia COUNTRY=mongolia

---

frontend/src/components/DataDrawer/DataTable/index.tsx
frontend/src/components/NavBar/MenuSwitch/index.tsx

This fixes issue [enter issue number]. Closes #683 
- Use mongolia country

Include missing translations in table view COUNTRY=mongolia

---

frontend/src/components/Common/BoundaryDropdown/index.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
frontend/src/components/MapView/LeftPanel/ChartsPanel/index.test.tsx
frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx
frontend/src/components/MapView/LeftPanel/layersPanel/MenuSwitch/SwitchItem/LayerDownloadOptions.tsx

This fixes issue [#744].
FIxes the data shift columns in CSV when data are missing.
Also this commit fixes some unique key maps in various components that throws errors on the console.

Fix CSV data shift when data are missing

---

api/app/kobo.py
api/app/main.py
api/app/tests/test_api.py
api/docker-compose.deploy.yml

fix: Add filters to the kobo date query

---

frontend/src/components/MapView/LeftPanel/ChartsPanel/index.test.tsx
frontend/src/components/MapView/LeftPanel/ChartsPanel/index.tsx

This fixes issue [#744].
FIxes the data shift columns in CSV when data are missing.

hotfix: CSV data shift

---

frontend/src/config/zimbabwe/prism.json

Fix map positioning for Zimbabwe and new UX.

Shift initial map position; COUNTRY=zimbabwe

---

common/src/base/test.ts
common/src/utils/parse.ts
common/src/wcs/WCSLayer/index.ts
common/src/wcs/utils/index.ts
common/src/wms/utils/index.ts
frontend/.eslintrc
frontend/src/components/Common/BoundaryDropdown/index.tsx
frontend/src/components/Common/BoundaryDropdown/searchBar.tsx
frontend/src/context/mapStateSlice/selectors.ts

Tentative fix for boundary options Menu Items and SearchBar

Fix/773 boundary options update rendering keys; COUNTRY=cambodia

---

frontend/src/components/Common/MultiOptionsButton/index.tsx
frontend/src/components/Common/ReportDialog/ReportDocLegend.tsx
frontend/src/components/Common/ReportDialog/ReportDocTable.tsx
frontend/src/components/Common/ReportDialog/ReportDocTableHeader.tsx
frontend/src/components/Common/ReportDialog/index.tsx
frontend/src/components/Common/ReportDialog/reportDoc.tsx
frontend/src/components/Common/ReportDialog/types.ts
frontend/src/components/Common/ReportDialog/types.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/ExposureAnalysisTable/index.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/AnalysisTable/index.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/ExposureAnalysisActions/index.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/index.tsx
frontend/src/components/MapView/Legends/AnalysisDownloadButton.tsx
frontend/src/components/MapView/Legends/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/utils.ts
frontend/src/context/analysisResultStateSlice.ts
frontend/src/utils/analysis-utils.ts

Tentative fixes to exposure analysis table data. 
- Exposure Analysis Sortable Columns
- Exposure Analysis Table Admin Names Concatenation
Needs a bit more work on fixing the Pdf creation. It is still a work in progress

Concatenate admin names in Exposure Analysis tables

---

frontend/public/data/rbd/about.md

Minor changes to text in the about page for RBD

Update about text; COUNTRY=rbd

---

frontend/src/config/srilanka/index.ts

Fix an error in index.ts default boundary config

fix boundary config; COUNTRY=srilanka

---

frontend/src/config/myanmar/layers.json
frontend/src/config/myanmar/prism.json

This PR adds tropical storm layers back to the configuration for PRISM Myanmar

add tropical storm layers back for Myanmar

---

frontend/src/config/cambodia/layers.json
frontend/src/config/colombia/layers.json
frontend/src/config/mozambique/layers.json
frontend/src/config/myanmar/layers.json
frontend/src/config/namibia/layers.json
frontend/src/config/srilanka/layers.json
frontend/src/config/tajikistan/layers.json

This fixes an error where population raster layers were incorrectly scaled

fix population raster scale error; COUNTRY=myanmar

---

README.md

This PR adds text about boundary files in the main README file

Update README with a note about boundary files

---

frontend/src/components/MapView/Legends/layerContentPreview.tsx
frontend/src/components/NavBar/About/index.tsx
frontend/src/components/NavBar/ContentDialog/index.tsx
frontend/src/utils/load-layer-utils.ts

This branch fixes the scrolling of the anchor element of the `Legend` component when the layer has `contentPath`.

Fixed Scroll to anchor link of layer contentPath; COUNTRY=myanmar

---

frontend/src/components/MapView/DateSelector/DateSelectorInput/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/DateSelector/DateSelectorInput/index.test.tsx
frontend/src/components/MapView/DateSelector/DateSelectorInput/index.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/TooltipItem/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/DateSelector/TimelineItems/TooltipItem/index.test.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/TooltipItem/index.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/DateSelector/TimelineItems/index.test.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
frontend/src/components/MapView/DateSelector/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/DateSelector/index.tsx

This adds a warning message when a date change cannot be accessed or is not intersecting with all layers' available dates.

Show message when a date change cannot be accessed; COUNTRY=cambodia

---

frontend/src/components/MapView/index.tsx
frontend/src/context/mapStateSlice/index.ts

This fixes issue #857 and #858

fix admin level data bug; COUNTRY=mozambique

---

frontend/src/utils/fetch-with-timeout.ts
frontend/src/utils/server-utils.ts

This branch fixes the external server periodacally connection for GetCapabilities Requests

Handle WMS server errors graciously

---

frontend/src/components/DataViewer/index.tsx
frontend/src/components/MapView/index.tsx

As it happened the DataViewer component was actually rendering the charts from the Map Tooltip actions, hence there was the error with the charts. In the process of an unused components cleanup I mistakenly removed the DataDrawer component. I restored it and seems that everything is working as expected.

Restore DataViewer to display charts from map tooltip (cambodia)

---

api/app/main.py
api/app/raster_utils.py
api/app/zonal_stats.py

- Fix the intersect_percentage calculation by considering nodata pixels as valid for the denominator.
- Add intersect_area statistic

Fix intersect_percentage API

---

api/app/main.py
api/app/report.py
api/app/tests/test_playwright_renderer.py
frontend/src/components/Common/LoadingBlinkingDots/index.tsx
frontend/src/components/Common/ReportDialog/index.tsx
frontend/src/components/MapView/LeftPanel/AnalysisPanel/ExposureAnalysisActions/index.tsx

- Rename functions
- Add white blinking dots

Pdf report - rename backend functions; COUNTRY=cambodia

---

api/app/kobo.py
api/docker-compose.develop.yml

Add kobo submission_id in API response

Add kobo submission_id

---

frontend/src/config/tanzania/prism.json

Fixing an error in the setup of rainfall layers for Tanzania

fix rainfall layer configuration; COUNTRY=tanzania

---

.github/pull_request_template.md

This should improve #969 a little (though not fix it entirely).
I just added a checklist to remind PR authors to test their code on 3 different countries, to help catch obvious bugs before review.

Update PR template with minimal checklist

---

frontend/src/config/zimbabwe/layers.json
frontend/src/config/zimbabwe/prism.json

Add configuration changes for Zimbabwe including layer ordering, and addition of 7-month products

configuration updates; COUNTRY=zimbabwe

---

frontend/src/config/mozambique/layers.json

Moz layer updates; COUNTRY=mozambique

---

frontend/src/config/zimbabwe/layers.json
frontend/src/config/zimbabwe/prism.json

Update text in layers.json and prism.json to clarify MSD vs CHIRPS data

layer label updates; COUNTRY=zimbabwe

---

frontend/package.json
frontend/yarn.lock

Upgrade node-notifier

---

.github/workflows/frontend.yml
frontend/public/data/zimbabwe/zim_fs_2021.json

There was a mismatch in data type for the admin level code in the json file for food security layers

change admin code to string in admin level food security dataset; COUNTRY=zimbabwe

---

frontend/src/config/zimbabwe/layers.json

Minor changes to layer names / descriptions for Zimbabwe

Fix layer descriptions; COUNTRY=zimbabwe

---

frontend/src/components/MapView/Map/index.tsx
frontend/src/components/NavBar/PrintImage/__snapshots__/index.test.tsx.snap
frontend/src/components/NavBar/PrintImage/image.tsx
frontend/src/muiTheme.tsx

@echaidemenos I think it will be more sustainable to redraw the map with a logic like this compared to what's currently on #1074. What do you think? Happy to discuss tomorrow when you're available.

Map copy for redraw

---

frontend/src/components/MapView/MapTooltip/PopupContent.tsx

Hide Kobo DMP metadata; COUNTRY=cambodia

---

frontend/src/components/Common/BoundaryDropdown/goto.tsx
frontend/src/components/MapView/ExtraFeature/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/config/jordan/prism.json
frontend/src/utils/map-utils.ts

Fix alert selection after switching language; COUNTRY=jordan

---

frontend/src/config/mozambique/layers.json

Configuration update fixing daily rainfall legend and scale factor.

update daily rainfall style and scale; COUNTRY=mozambique

---

frontend/src/config/mozambique/layers.json
frontend/src/config/mozambique/prism.json

Add additional blended rainfall layers

rainfall layer configuration updates; COUNTRY=mozambique

---

frontend/src/components/MapView/Layers/AnticipatoryActionLayer/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/index.test.tsx

AA - Add map onClick

---

frontend/src/components/MapView/Layers/AnticipatoryActionLayer/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/index.test.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/DistrictView/utils.ts
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/index.test.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Timeline/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Timeline/index.test.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Timeline/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Timeline/utils.ts
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/test.utils.ts
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/utils.tsx
frontend/src/context/anticipatoryActionStateSlice/index.ts
frontend/src/context/anticipatoryActionStateSlice/types.ts

AA - Add Timeline View

---

frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AALegend/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AALegend/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HowToReadModal/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HowToReadModal/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap
frontend/src/config/mozambique/prism.json
frontend/src/config/shared/portuguese.json

Add "Mild" to AA legend

---

frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AAIcon.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AALegend/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AALegend/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Forecast/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Forecast/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/index.tsx
frontend/src/components/MapView/Legends/LegendItemsList.tsx
frontend/src/components/MapView/Legends/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/Legends/index.tsx
frontend/src/components/NavBar/PrintImage/__snapshots__/index.test.tsx.snap
frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap

AA - Adjust legend style

---

frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Forecast/index.test.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/Forecast/utils.ts
frontend/src/components/MapView/Legends/LegendItemsList.tsx
frontend/src/components/NavBar/PrintImage/__snapshots__/index.test.tsx.snap
frontend/src/components/NavBar/PrintImage/image.tsx

Add logo to print mode

---

frontend/src/config/sudan/prism.json

Add land surface temperature layers in prism.json

Add LST layers; COUNTRY=sudan

---

frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/HomeTable/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/config/mozambique/prism.json
frontend/src/context/anticipatoryActionStateSlice/utils.ts

AA - Use S3 for Mozambique

---

frontend/src/config/cambodia/prism.json

add rainfall forecast layers; COUNTRY=cambodia

---

frontend/src/components/MapView/LeftPanel/index.tsx
frontend/src/components/MapView/__snapshots__/index.test.tsx.snap
frontend/src/components/NavBar/__snapshots__/index.test.tsx.snap
frontend/src/config/mozambique/prism.json

Fix boundary selection outside of alert mode

---

frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx

Add storm lines

---

frontend/src/components/MapView/DateSelector/TimelineItems/AAStormTimelineItem/index.tsx

update ticks to add ready state and to match figma designs
https://www.figma.com/design/Xe8H1GuVMJUsIi4JNTYPVo/WFP-Anticipatory-Action-(AA)?node-id=1769-3874&t=aR33Bq4qQWwmkcJR-0

Aa update ticks

---

frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AnticipatoryActionStormPanel/ActivationTriggerView/index.tsx
frontend/src/context/anticipatoryAction/AAStormStateSlice/parsedStormDataTypes.ts
frontend/src/context/anticipatoryAction/AAStormStateSlice/rawStormDataTypes.ts
frontend/src/context/anticipatoryAction/AAStormStateSlice/utils.ts

[DIKELEDI.geojson](https://github.com/user-attachments/files/18565346/DIKELEDI.json)

Add merged geojson for download

---

alerting/docker-compose.yml
alerting/ormconfig.ts
alerting/package.json
alerting/src/aa-storm-alert/worker.test.ts
alerting/yarn.lock

Upgrade PostgreSQL to v16

---

alerting/docker-compose.yml
alerting/ormconfig.ts
alerting/package.json
alerting/src/aa-storm-alert/worker.test.ts
alerting/yarn.lock
frontend/src/components/MapView/DateSelector/TimelineItems/TimelineLabel/index.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/__snapshots__/index.test.tsx.snap
frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
frontend/src/components/MapView/DateSelector/index.tsx
frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/AAStormDatePopup/index.tsx
frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
frontend/src/context/anticipatoryAction/AAStormStateSlice/utils.ts

Adapt to new file structure, the forecast date point is now deduped and only available as the first forecast point.
Upgrade PostgreSQL to v16

AA storm - Adapt to new api data structure

---

alerting/src/aa-storm-alert/alert.ts
alerting/src/aa-storm-alert/worker.test.ts
alerting/src/aa-storm-alert/worker.ts
alerting/src/templates/storm-alert.ejs
frontend/src/components/MapView/DateSelector/TimelineItems/AAStormTooltipContent/index.tsx
frontend/src/components/MapView/DateSelector/TimelineItems/index.tsx
frontend/src/components/MapView/Layers/AnticipatoryActionStormLayer/index.tsx
frontend/src/components/MapView/LeftPanel/AnticipatoryActionPanel/AnticipatoryActionStormPanel/index.tsx
frontend/src/context/anticipatoryAction/AAStormStateSlice/utils.ts

Update readiness coloring:
- color districts that would be activated in blue
- hide activation NA in the left panel

Update readiness coloring

---

frontend/src/config/malawi/prism.json

add AA staging URL; COUNTRY=malawi
